# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: allanhenderson
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: vs-translate
service: aws-translate-api

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  environment: ${file(./config/env.${self:provider.stage}.yml)}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - translate:TranslateText
          Resource: "*"

plugins:
  - serverless-offline

functions:
  translate:
    handler: src/handler.translate
    events:
      - http:
          path: translate
          method: post
          cors: true
    environment:
      STAGE: ${self:provider.stage}
      SERVICE_NAME: translate-api
      LOG_LEVEL: ${self:provider.environment.LOG_LEVEL}

custom:
  dotenv:
    path: ./config/.env.${self:provider.stage}

package:
  patterns:
    - '!**/*.test.js'
    - '!coverage/**'
    - '!docs/**'
    - '!.github/**'
    - '!.git/**'
    - '!.env*'